default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mehdi_ayoub
  password: password
  socket: /tmp/mysql.sock # path

development:
  <<: *default
  database: wakilni-project_development

test:
  <<: *default
  database: wakilni-project_test

production:
  <<: *default
  database: wakilni-project_production
  host: production_host  # i will change if i pushed to production
